<?php

require_once(dirname(__FILE__) . '/../../classes/GridClass.php');

class AdminCaLetSensController extends ModuleAdminController
{
    public $html = '';
    public $path_tpl;
    public $smarty;

    public function __construct()
    {
        //Tools::redirectAdmin('index.php?controller=AdminStats&module=cdmoduleca&token='.Tools::getAdminTokenLite('AdminStats'));
        $this->module = 'cdmoduleca';
        $this->bootstrap = true;
        $this->className = 'AdminCaLetSens';
        $this->lang = false;
        $this->context = Context::getContext();
        $this->smarty = $this->context->smarty;
        $this->path_tpl = _PS_MODULE_DIR_ . 'cdmoduleca/views/templates/hook/';
        parent::__construct();
    }



    public function initContent()
    {
        $this->context->controller->addCSS(_PS_MODULE_DIR_ . 'cdmoduleca/views/css/statscdmoduleca.css');
        $engine_params = array(
            'id' => 'id_order',
            'title' => $this->module->displayName,
            'columns' => $this->module->columns,
            'defaultSortColumn' => $this->module->default_sort_column,
            'defaultSortDirection' => $this->module->default_sort_direction,
            'emptyMessage' => $this->module->empty_message,
            'pagingMessage' => $this->module->paging_message,
            'limit' => $this->module->limit,
        );


        $g = new GridClass();

        $g->data = array(
            'idGroupEmployee' => $this->module->getGroupeEmployee($this->module->idFilterCoach),
            'idFilterCoach' => $this->module->idFilterCoach,
            'idFilterCodeAction' => $this->module->idFilterCodeAction,
            'commandeValid' => $this->module->commandeValid,
            'lang' => $this->module->lang,
            'CodeActionABO' => $this->module->getCodeActionByName('ABO'),
            'date' => $this->module->getDate()
        );

        $this->context->smarty->assign(array(
            'CSVLink' => Tools::safeOutput($_SERVER['REQUEST_URI'] . '&export=1')
        ));

        $this->html .= $this->context->smarty->fetch($this->path_tpl . 'headerstats.tpl');

        $this->html .= $g->engine($engine_params);

        if (Tools::getValue('export')) {
            $g->csvExport($engine_params);
        }



//        $this->html .= $this->display(__FILE__, 'headerstats.tpl');
//        $this->html .= $this->syntheseCoachs();
//        $this->html .= $this->display(__FILE__, 'footerstats.tpl');

//        $this->html = 'Admin Stats';
        $this->content = $this->html;
        return parent::initContent(); // TODO: Change the autogenerated stub
    }

}
